{% set name = "cxxtest" %}
{% set version = "4.4" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/CxxTest/cxxtest/releases/download/{{ version }}/cxxtest-{{ version }}.tar.gz
    sha256: 1c154fef91c65dbf1cd4519af7ade70a61d85a923b6e0c0b007dc7f4895cf7d8

build:
    number: 1002

requirements:
  build:
   - {{ compiler('c') }}
   - {{ compiler('cxx') }}
  host:
   - python
   - setuptools
  run:
   - python

test:
    requires:
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
    source_files:
        - doc/examples/MyTestSuite1.h

about:
    home: http://cxxtest.com/
    license: LGPLv3
    license_file: COPYING
    summary: 'CxxTest Unit Testing Framework.'
    description: |
      CxxTest is a unit testing framework for C++ that is similar in spirit to
      JUnit, CppUnit, and xUnit. CxxTest is easy to use because it does not
      require precompiling a CxxTest testing library, it employs no advanced 
      features of C++ (e.g. RTTI) and it supports a very flexible form of test
      discovery.
    doc_url: http://cxxtest.com/guide.html
    dev_url: https://github.com/CxxTest/cxxtest

extra:
    recipe-maintainers:
      - swainn
      - Tsubashi
      - alemon-aquaveo
      - gagelarsen
