travis:
  secure:
    BINSTAR_TOKEN: G6A7mcAz2ESwLXuNFVhKX5zghASvLPs+3nrhFVbSUS+3fdtklEjkSEi3qhIwIYA0W1cXuK2D7WLIyw0uQNomXqq+WpzWGrMFdsKGOrTHNogcKLT3l0oD2d+QU1hoqjte+3a+J4iM6bbwC0Pb/nLs/5RvyXu8H/75cQw1B5iVuutcN7ZDoTBi2k17/tEyUj4tBFSAAOMDSl439AcaFJshR7DUPEZ4/sviACYJkNUl1TRQ/idYRpT45pUeRkv3MiQb5GxpKnSAYFDLTGyhLh5c2k2cdlxnjhAzqeeHblALtq/M7YIfx3S8MUi/iWYOt22sDntHnUQOsR/hFXXR/v6JTm1NVbZNVS5EOx4t1kzudz5p1U4nQRR1QWz5QWUAGvbRvqjB+35xxxbdmYfkGxVs6GHfqP3SabSJRa7KCFJFk3LfNfgq8LaKyzFWBjWlIm5eI1PPkSChSBN03Cs5Vz52bw17ZyEjfwd02CJvBDJogP2G0xw/rYy7YYhbGU1C6tkuQwTgt68ZqRxV8KpAiIh/py7eUCoCSXBdtpRKkCn8Hy/9/wDpuEcaABtvfin7e5USFgIzjsCQjDYzFGczCPtK+li36aiAp2BIqtR5p+SLmysc0r68myYI9rVeT5gWdXp0VMb87nG24bxxa7ajlf1qoPjFhEQBNsB9VbPrVwV3hcs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
